name = "analytics_with_cloudflare"
main = "src/index.ts"
compatibility_date = "2023-12-03"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "<DATABASE_NAME>"
database_id = "<unique-ID-for-your-database>"